### ISSUE TITLE
pyliblzma dependency

### ISSUE THREAD

**Issue by SamPenrose** [vitillo/python_moztelemetry#4]
The project depends on pyliblzma. I couldn't get it to install by adding it to setup.py, but "pip install" worked.

**Comment by mreid-moz** [comment]
Can it be swapped for [backports.lzma](https://pypi.python.org/pypi/backports.lzma/)? would that work with setup.py?

**Comment by vitillo** [comment]
Given that this is required only for telemetry v2, which will soon be deprecated by the v4 data format, I am not sure it's worth spending any efforts into fixing this.

**Comment by SamPenrose** [comment]
Works for me!
