### ISSUE TITLE
telemetry-server dependency

### ISSUE THREAD

**Issue by SamPenrose** [vitillo/python_moztelemetry#5]
The project appears to depend on https://github.com/mozilla/telemetry-server 

grep -r telemetry moztelemetry | grep import
moztelemetry/filter_service.py:from telemetry.telemetry_schema import TelemetrySchema
moztelemetry/heka_message_parser.py:from telemetry.util.heka_message import unpack, BacktrackableFile

**Comment by vitillo** [comment]
The project depends on [telemetry-tools](https://github.com/mozilla/telemetry-tools), which is specified in setup.py.
