### ISSUE TITLE
spark.py/__get_merged_histograms() clashing with v4?

### ISSUE THREAD

**Issue by SamPenrose** [vitillo/python_moztelemetry#6]
I have some v4 pings and am counting:
  p['payload']['keyedHistograms']['SEARCH_COUNTS']
I can directly access that path. But after:
  v4_pings = get_pings_properties(pings, ['payload/keyedHistograms/SEARCH_COUNTS'])
I hit a traceback (below). It looks like:
  https://github.com/vitillo/python_moztelemetry/blob/master/moztelemetry/spark.py#L345
should read:
  assert((len(path) == 2 and path[0] in ("histograms", "keyedHistograms"))
to pass that test, although maybe the rest of the function does not match the v4 histogram structure -- not sure at a glance.

**Comment by vitillo** [comment]
Keyed histograms can be accessed only by specifying explicitely a label, e.g. "payload/keyedHistograms/SEARCH_COUNTS/yahoo...". Please have a look at the [tutorial](http://nbviewer.ipython.org/github/vitillo/emr-bootstrap-spark/blob/master/Unified%20Telemetry-FHR%20Hello%20World.ipynb#Histograms).
